--- #YAML:1.0
name:               CGI-ExtDirect
version:            1.11
abstract:           RPC::ExtDirect gateway for CGI
author:
    - Alexander Tokarev <tokarev@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    CGI::Test:   0.3
    Test::More:  0
requires:
    RPC::ExtDirect:  1.21
resources:
    bugtracker:  http://github.com/nohuhu/CGI-ExtDirect/issues
    repository:  http://github.com/nohuhu/CGI-ExtDirect
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
