---
abstract: 'RPC::ExtDirect gateway for CGI'
author:
  - 'Alexander Tokarev <tokarev@cpan.org>'
build_requires:
  CGI::Test: 0.3
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-ExtDirect
no_index:
  directory:
    - t
    - inc
requires:
  RPC::ExtDirect: 2.02
resources:
  bugtracker: http://github.com/nohuhu/CGI-ExtDirect/issues
  repository: http://github.com/nohuhu/CGI-ExtDirect
version: 2.03
